# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 588008f774da6b7667b24ec3417fd656869121c9c32af39e4781978fff4a7154c397c5c2f00d9230ecbde64950909d041347d20c709899939d6b521e4ca0bcf9

test:
  secret_key_base: d7fb116a726aec9dc9c04ac5d7252a5b9d0a9baf55ca7dd0f061802df7bc32f22432e412d63858ebc1caee482d579bfefa3ad7854b8c8f44470b24803d261069

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
